package cn.itcast.service.cargo;

import cn.itcast.domain.cargo.Invoice;
import cn.itcast.domain.cargo.InvoiceExample;
import com.github.pagehelper.PageInfo;

import java.util.List;

public interface InvoiceService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_invoice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String invoiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_invoice
     *
     * @mbg.generated
     */
    int insert(Invoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_invoice
     *
     * @mbg.generated
     */
    int insertSelective(Invoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_invoice
     *
     * @mbg.generated
     */
    List<Invoice> selectByExample(InvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_invoice
     *
     * @mbg.generated
     */
    Invoice selectByPrimaryKey(String invoiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_invoice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Invoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_invoice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Invoice record);
    //分页查询
    public PageInfo findAll(InvoiceExample example, int page, int size);
    //更新
    void update(Invoice invoice);
    //根据id查询
    Invoice findById(String id);
    //新增发票
    void save(Invoice invoice);

    void delete(String id);
}
